# Generated by Django 5.0.3 on 2024-04-05 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_title', models.CharField(max_length=100)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='materials.category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='materials.category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.IntegerField()),
                ('option_one', models.CharField(blank=True, max_length=100)),
                ('option_two', models.CharField(blank=True, max_length=100)),
                ('option_three', models.CharField(blank=True, max_length=100)),
                ('course', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='materials.course')),
            ],
        ),
    ]
